<fieldset class="fieldset account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <div class="field dni required">
        <label for="dni" class="label"><span><?php /* @escapeNotVerified */ echo __('DNI') ?></span></label>
        <div class="control">
            <input type="text" name="dni" id="dni" value="<?= $this->getDni()?>" title="<?php /* @escapeNotVerified */ echo __('DNI') ?>" class="input-text" data-validate="{required:true}" autocomplete="off">
        </div>
    </div>
</fieldset>
